server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OneJane/SpringCloudDemo/     # 配置git仓库的地址
          search-paths: spring-cloud-config-git/config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: onejane                                        # git仓库的账号
          password: Wangjian123456                                    # git仓库的密码
  rabbitmq:
    host: 192.168.3.233
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址


management:
  security:
     enabled: false

